name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Searx-ng
        run: |
          cd searxng
          docker build -t searxng .
          docker run -d -p 8888:8888 searxng

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          echo "searxng.example.com" > searxng/CNAME
          cd searxng
          git add CNAME
          git commit -m "Add CNAME file for custom domain"
          git push origin gh-pages

      - name: Clean up Docker container
        run: docker stop $(docker ps -q)
